# Generated by Django 5.2.6 on 2025-09-18 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PTAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('member', models.ForeignKey(limit_choices_to={'role': 'member'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_pt', to=settings.AUTH_USER_MODEL)),
                ('pt', models.ForeignKey(limit_choices_to={'role': 'pt'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('pt', 'member')},
            },
        ),
    ]
