# Generated by Django 5.2.6 on 2025-09-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pay_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
