# Generated by Django 5.2.6 on 2025-09-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_pay_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='request_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
