# Generated by Django 5.2.6 on 2025-09-22 09:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='gif_url',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='video_url',
        ),
        migrations.AddField(
            model_name='exercise',
            name='gif',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
