# Generated by Django 5.2.6 on 2025-09-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_userworkoutprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='description',
        ),
        migrations.AddField(
            model_name='exercise',
            name='instructions',
            field=models.JSONField(blank=True, help_text='Các bước thực hiện, lưu dưới dạng một danh sách các chuỗi. VD: ["Bước 1: ...", "Bước 2: ..."]', null=True),
        ),
    ]
