# Generated by Django 5.2.6 on 2025-09-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_remove_exercise_description_exercise_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='ai_supported',
            field=models.BooleanField(default=False, help_text='Đánh dấu nếu bài tập này được hỗ trợ bởi AI Coach'),
        ),
    ]
