# Generated by Django 5.2.6 on 2025-10-05 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_exercise_ai_supported'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWorkoutPlanAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.OneToOneField(limit_choices_to={'role': 'member'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_plan', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='workouts.workoutplan')),
                ('pt', models.ForeignKey(limit_choices_to={'role': 'pt'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_plans_by_pt', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('member', 'plan')},
            },
        ),
    ]
