# Generated by Django 5.2.6 on 2025-10-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_userworkoutplanassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='rep_counting_logic',
            field=models.CharField(blank=True, help_text='Tên của hàm logic đếm rep phía frontend s', max_length=50, null=True),
        ),
    ]
