# Generated by Django 5.2.6 on 2025-09-20 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(blank=True, help_text='Height in cm', null=True)),
                ('initial_weight', models.FloatField(blank=True, help_text='Initial weight in kg', null=True)),
                ('goal', models.TextField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memberprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
