# Generated by Django 5.2.6 on 2025-10-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_memberprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='expo_push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
