# Generated by Django 5.2.6 on 2025-09-19 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0002_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membershippackage',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL ảnh minh họa cho gói tập', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pt',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'pt'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pt_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
